version: '3.8'

services:
  high-performance-server:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SERVER_TYPE=libevent
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    
  # 可选：运行不同类型的服务器
  libuv-server:
    build: .
    ports:
      - "8081:8080"
    command: ["./libuv/libuv_echo_server"]
    restart: unless-stopped
    
  libev-server:
    build: .
    ports:
      - "8082:8080"
    command: ["./libev/libev_echo_server"]
    restart: unless-stopped
    
  boost-asio-server:
    build: .
    ports:
      - "8083:8080"
    command: ["./boost_asio/boost_asio_echo_server"]
    restart: unless-stopped