package imports

import (
	"math"
	"reflect"

	"git.woa.com/vasd_masc_ba/YitihuaOteam/base/gofun/register"
)

var _ = reflect.Int

func init() {
	register.AddPackage("math", "math",
		register.NewFunction("Abs", math.Abs, ""),
		register.NewFunction("Acos", math.Acos, ""),
		register.NewFunction("Acosh", math.Acosh, ""),
		register.NewFunction("Asin", math.Asin, ""),
		register.NewFunction("Asinh", math.Asinh, ""),
		register.NewFunction("Atan", math.Atan, ""),
		register.NewFunction("Atan2", math.Atan2, ""),
		register.NewFunction("Atanh", math.Atanh, ""),
		register.NewFunction("Cbrt", math.Cbrt, ""),
		register.NewFunction("Ceil", math.Ceil, ""),
		register.NewFunction("Copysign", math.Copysign, ""),
		register.NewFunction("Cos", math.Cos, ""),
		register.NewFunction("Cosh", math.Cosh, ""),
		register.NewFunction("Dim", math.Dim, ""),
		register.NewConst("E", math.E, ""),
		register.NewFunction("Erf", math.Erf, ""),
		register.NewFunction("Erfc", math.Erfc, ""),
		register.NewFunction("Erfcinv", math.Erfcinv, ""),
		register.NewFunction("Erfinv", math.Erfinv, ""),
		register.NewFunction("Exp", math.Exp, ""),
		register.NewFunction("Exp2", math.Exp2, ""),
		register.NewFunction("Expm1", math.Expm1, ""),
		register.NewFunction("FMA", math.FMA, ""),
		register.NewFunction("Float32bits", math.Float32bits, ""),
		register.NewFunction("Float32frombits", math.Float32frombits, ""),
		register.NewFunction("Float64bits", math.Float64bits, ""),
		register.NewFunction("Float64frombits", math.Float64frombits, ""),
		register.NewFunction("Floor", math.Floor, ""),
		register.NewFunction("Frexp", math.Frexp, ""),
		register.NewFunction("Gamma", math.Gamma, ""),
		register.NewFunction("Hypot", math.Hypot, ""),
		register.NewFunction("Ilogb", math.Ilogb, ""),
		register.NewFunction("Inf", math.Inf, ""),
		register.NewFunction("IsInf", math.IsInf, ""),
		register.NewFunction("IsNaN", math.IsNaN, ""),
		register.NewFunction("J0", math.J0, ""),
		register.NewFunction("J1", math.J1, ""),
		register.NewFunction("Jn", math.Jn, ""),
		register.NewFunction("Ldexp", math.Ldexp, ""),
		register.NewFunction("Lgamma", math.Lgamma, ""),
		register.NewConst("Ln10", math.Ln10, ""),
		register.NewConst("Ln2", math.Ln2, ""),
		register.NewFunction("Log", math.Log, ""),
		register.NewFunction("Log10", math.Log10, ""),
		register.NewConst("Log10E", math.Log10E, ""),
		register.NewFunction("Log1p", math.Log1p, ""),
		register.NewFunction("Log2", math.Log2, ""),
		register.NewConst("Log2E", math.Log2E, ""),
		register.NewFunction("Logb", math.Logb, ""),
		register.NewFunction("Max", math.Max, ""),
		register.NewConst("MaxFloat32", math.MaxFloat32, ""),
		register.NewConst("MaxFloat64", math.MaxFloat64, ""),
		register.NewConst("MaxInt16", math.MaxInt16, ""),
		register.NewConst("MaxInt32", math.MaxInt32, ""),
		register.NewConst("MaxInt64", math.MaxInt64, ""),
		register.NewConst("MaxInt8", math.MaxInt8, ""),
		register.NewConst("MaxUint16", math.MaxUint16, ""),
		register.NewConst("MaxUint32", math.MaxUint32, ""),
		register.NewConst("MaxUint64", uint(math.MaxUint64), ""),
		register.NewConst("MaxUint8", math.MaxUint8, ""),
		register.NewFunction("Min", math.Min, ""),
		register.NewConst("MinInt16", math.MinInt16, ""),
		register.NewConst("MinInt32", math.MinInt32, ""),
		register.NewConst("MinInt64", math.MinInt64, ""),
		register.NewConst("MinInt8", math.MinInt8, ""),
		register.NewFunction("Mod", math.Mod, ""),
		register.NewFunction("Modf", math.Modf, ""),
		register.NewFunction("NaN", math.NaN, ""),
		register.NewFunction("Nextafter", math.Nextafter, ""),
		register.NewFunction("Nextafter32", math.Nextafter32, ""),
		register.NewConst("Phi", math.Phi, ""),
		register.NewConst("Pi", math.Pi, ""),
		register.NewFunction("Pow", math.Pow, ""),
		register.NewFunction("Pow10", math.Pow10, ""),
		register.NewFunction("Remainder", math.Remainder, ""),
		register.NewFunction("Round", math.Round, ""),
		register.NewFunction("RoundToEven", math.RoundToEven, ""),
		register.NewFunction("Signbit", math.Signbit, ""),
		register.NewFunction("Sin", math.Sin, ""),
		register.NewFunction("Sincos", math.Sincos, ""),
		register.NewFunction("Sinh", math.Sinh, ""),
		register.NewConst("SmallestNonzeroFloat32", math.SmallestNonzeroFloat32, ""),
		register.NewConst("SmallestNonzeroFloat64", math.SmallestNonzeroFloat64, ""),
		register.NewFunction("Sqrt", math.Sqrt, ""),
		register.NewConst("Sqrt2", math.Sqrt2, ""),
		register.NewConst("SqrtE", math.SqrtE, ""),
		register.NewConst("SqrtPhi", math.SqrtPhi, ""),
		register.NewConst("SqrtPi", math.SqrtPi, ""),
		register.NewFunction("Tan", math.Tan, ""),
		register.NewFunction("Tanh", math.Tanh, ""),
		register.NewFunction("Trunc", math.Trunc, ""),
		register.NewFunction("Y0", math.Y0, ""),
		register.NewFunction("Y1", math.Y1, ""),
		register.NewFunction("Yn", math.Yn, ""),
	)
}
