package pkgs

// ImportPkgs 需要导入的包的路径，如果是vendor目录下的包，需要加上vendor/
var ImportPkgs = map[string][]string{
	"bytes":           []string{},
	"container/heap":  []string{},
	"container/list":  []string{},
	"container/ring":  []string{},
	"crypto/md5":      []string{},
	"encoding/base64": []string{},
	"encoding/hex":    []string{},
	"encoding/xml":    []string{},
	"errors":          []string{},
	"fmt":             []string{},
	"html":            []string{},
	"math":            []string{},
	"math/rand":       []string{},
	"net/http":        []string{},
	"net/url":         []string{},
	"regexp":          []string{},
	"sort":            []string{},
	"strconv":         []string{},
	"strings":         []string{},
	"time":            []string{},
	"unicode":         []string{},
	"unicode/utf8":    []string{},
	"unicode/utf16":   []string{},
	"sync":            []string{},
	"sync/atomic":     []string{},

	"crypto/sha1":     []string{},
	"encoding/json":   []string{},
	"encoding/binary": []string{},
	"io/ioutil":       []string{"io"},
	"io":              []string{},
	"html/template":   []string{},
	"path":            []string{},
	"mime/multipart":  []string{},
	"crypto/des":      []string{},
	"crypto/cipher":   []string{},
	"crypto/tls":      []string{},

	"github.com/json-iterator/go": []string{},
}
