// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetObjectCount():Promise<number>;

export function Greet(arg1:string):Promise<string>;

export function ProcessCommand(arg1:string):Promise<string>;

export function SetObjectCount(arg1:number):Promise<void>;
