// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetObjectCount() {
  return window['go']['main']['App']['GetObjectCount']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ProcessCommand(arg1) {
  return window['go']['main']['App']['ProcessCommand'](arg1);
}

export function SetObjectCount(arg1) {
  return window['go']['main']['App']['SetObjectCount'](arg1);
}
