package imports

import (
	"reflect"
	"unicode"

	"git.woa.com/vasd_masc_ba/YitihuaOteam/base/gofun/register"
)

var _ = reflect.Int

func init() {
	register.AddPackage("unicode", "unicode",
		register.NewVar("ASCII_Hex_Digit", &unicode.ASCII_Hex_Digit, reflect.TypeOf(unicode.ASCII_Hex_Digit), ""),
		register.NewVar("Adlam", &unicode.Adlam, reflect.TypeOf(unicode.Adlam), ""),
		register.NewVar("Ahom", &unicode.Ahom, reflect.TypeOf(unicode.Ahom), ""),
		register.NewVar("Anatolian_Hieroglyphs", &unicode.Anatolian_Hieroglyphs, reflect.TypeOf(unicode.Anatolian_Hieroglyphs), ""),
		register.NewVar("Arabic", &unicode.Arabic, reflect.TypeOf(unicode.Arabic), ""),
		register.NewVar("Armenian", &unicode.Armenian, reflect.TypeOf(unicode.Armenian), ""),
		register.NewVar("Avestan", &unicode.Avestan, reflect.TypeOf(unicode.Avestan), ""),
		register.NewVar("AzeriCase", &unicode.AzeriCase, reflect.TypeOf(unicode.AzeriCase), ""),
		register.NewVar("Balinese", &unicode.Balinese, reflect.TypeOf(unicode.Balinese), ""),
		register.NewVar("Bamum", &unicode.Bamum, reflect.TypeOf(unicode.Bamum), ""),
		register.NewVar("Bassa_Vah", &unicode.Bassa_Vah, reflect.TypeOf(unicode.Bassa_Vah), ""),
		register.NewVar("Batak", &unicode.Batak, reflect.TypeOf(unicode.Batak), ""),
		register.NewVar("Bengali", &unicode.Bengali, reflect.TypeOf(unicode.Bengali), ""),
		register.NewVar("Bhaiksuki", &unicode.Bhaiksuki, reflect.TypeOf(unicode.Bhaiksuki), ""),
		register.NewVar("Bidi_Control", &unicode.Bidi_Control, reflect.TypeOf(unicode.Bidi_Control), ""),
		register.NewVar("Bopomofo", &unicode.Bopomofo, reflect.TypeOf(unicode.Bopomofo), ""),
		register.NewVar("Brahmi", &unicode.Brahmi, reflect.TypeOf(unicode.Brahmi), ""),
		register.NewVar("Braille", &unicode.Braille, reflect.TypeOf(unicode.Braille), ""),
		register.NewVar("Buginese", &unicode.Buginese, reflect.TypeOf(unicode.Buginese), ""),
		register.NewVar("Buhid", &unicode.Buhid, reflect.TypeOf(unicode.Buhid), ""),
		register.NewVar("C", &unicode.C, reflect.TypeOf(unicode.C), ""),
		register.NewVar("Canadian_Aboriginal", &unicode.Canadian_Aboriginal, reflect.TypeOf(unicode.Canadian_Aboriginal), ""),
		register.NewVar("Carian", &unicode.Carian, reflect.TypeOf(unicode.Carian), ""),
		register.NewType("CaseRange", reflect.TypeOf(func(unicode.CaseRange) {}).In(0), ""),
		register.NewVar("CaseRanges", &unicode.CaseRanges, reflect.TypeOf(unicode.CaseRanges), ""),
		register.NewVar("Categories", &unicode.Categories, reflect.TypeOf(unicode.Categories), ""),
		register.NewVar("Caucasian_Albanian", &unicode.Caucasian_Albanian, reflect.TypeOf(unicode.Caucasian_Albanian), ""),
		register.NewVar("Cc", &unicode.Cc, reflect.TypeOf(unicode.Cc), ""),
		register.NewVar("Cf", &unicode.Cf, reflect.TypeOf(unicode.Cf), ""),
		register.NewVar("Chakma", &unicode.Chakma, reflect.TypeOf(unicode.Chakma), ""),
		register.NewVar("Cham", &unicode.Cham, reflect.TypeOf(unicode.Cham), ""),
		register.NewVar("Cherokee", &unicode.Cherokee, reflect.TypeOf(unicode.Cherokee), ""),
		register.NewVar("Co", &unicode.Co, reflect.TypeOf(unicode.Co), ""),
		register.NewVar("Common", &unicode.Common, reflect.TypeOf(unicode.Common), ""),
		register.NewVar("Coptic", &unicode.Coptic, reflect.TypeOf(unicode.Coptic), ""),
		register.NewVar("Cs", &unicode.Cs, reflect.TypeOf(unicode.Cs), ""),
		register.NewVar("Cuneiform", &unicode.Cuneiform, reflect.TypeOf(unicode.Cuneiform), ""),
		register.NewVar("Cypriot", &unicode.Cypriot, reflect.TypeOf(unicode.Cypriot), ""),
		register.NewVar("Cyrillic", &unicode.Cyrillic, reflect.TypeOf(unicode.Cyrillic), ""),
		register.NewVar("Dash", &unicode.Dash, reflect.TypeOf(unicode.Dash), ""),
		register.NewVar("Deprecated", &unicode.Deprecated, reflect.TypeOf(unicode.Deprecated), ""),
		register.NewVar("Deseret", &unicode.Deseret, reflect.TypeOf(unicode.Deseret), ""),
		register.NewVar("Devanagari", &unicode.Devanagari, reflect.TypeOf(unicode.Devanagari), ""),
		register.NewVar("Diacritic", &unicode.Diacritic, reflect.TypeOf(unicode.Diacritic), ""),
		register.NewVar("Digit", &unicode.Digit, reflect.TypeOf(unicode.Digit), ""),
		register.NewVar("Dogra", &unicode.Dogra, reflect.TypeOf(unicode.Dogra), ""),
		register.NewVar("Duployan", &unicode.Duployan, reflect.TypeOf(unicode.Duployan), ""),
		register.NewVar("Egyptian_Hieroglyphs", &unicode.Egyptian_Hieroglyphs, reflect.TypeOf(unicode.Egyptian_Hieroglyphs), ""),
		register.NewVar("Elbasan", &unicode.Elbasan, reflect.TypeOf(unicode.Elbasan), ""),
		register.NewVar("Elymaic", &unicode.Elymaic, reflect.TypeOf(unicode.Elymaic), ""),
		register.NewVar("Ethiopic", &unicode.Ethiopic, reflect.TypeOf(unicode.Ethiopic), ""),
		register.NewVar("Extender", &unicode.Extender, reflect.TypeOf(unicode.Extender), ""),
		register.NewVar("FoldCategory", &unicode.FoldCategory, reflect.TypeOf(unicode.FoldCategory), ""),
		register.NewVar("FoldScript", &unicode.FoldScript, reflect.TypeOf(unicode.FoldScript), ""),
		register.NewVar("Georgian", &unicode.Georgian, reflect.TypeOf(unicode.Georgian), ""),
		register.NewVar("Glagolitic", &unicode.Glagolitic, reflect.TypeOf(unicode.Glagolitic), ""),
		register.NewVar("Gothic", &unicode.Gothic, reflect.TypeOf(unicode.Gothic), ""),
		register.NewVar("Grantha", &unicode.Grantha, reflect.TypeOf(unicode.Grantha), ""),
		register.NewVar("GraphicRanges", &unicode.GraphicRanges, reflect.TypeOf(unicode.GraphicRanges), ""),
		register.NewVar("Greek", &unicode.Greek, reflect.TypeOf(unicode.Greek), ""),
		register.NewVar("Gujarati", &unicode.Gujarati, reflect.TypeOf(unicode.Gujarati), ""),
		register.NewVar("Gunjala_Gondi", &unicode.Gunjala_Gondi, reflect.TypeOf(unicode.Gunjala_Gondi), ""),
		register.NewVar("Gurmukhi", &unicode.Gurmukhi, reflect.TypeOf(unicode.Gurmukhi), ""),
		register.NewVar("Han", &unicode.Han, reflect.TypeOf(unicode.Han), ""),
		register.NewVar("Hangul", &unicode.Hangul, reflect.TypeOf(unicode.Hangul), ""),
		register.NewVar("Hanifi_Rohingya", &unicode.Hanifi_Rohingya, reflect.TypeOf(unicode.Hanifi_Rohingya), ""),
		register.NewVar("Hanunoo", &unicode.Hanunoo, reflect.TypeOf(unicode.Hanunoo), ""),
		register.NewVar("Hatran", &unicode.Hatran, reflect.TypeOf(unicode.Hatran), ""),
		register.NewVar("Hebrew", &unicode.Hebrew, reflect.TypeOf(unicode.Hebrew), ""),
		register.NewVar("Hex_Digit", &unicode.Hex_Digit, reflect.TypeOf(unicode.Hex_Digit), ""),
		register.NewVar("Hiragana", &unicode.Hiragana, reflect.TypeOf(unicode.Hiragana), ""),
		register.NewVar("Hyphen", &unicode.Hyphen, reflect.TypeOf(unicode.Hyphen), ""),
		register.NewVar("IDS_Binary_Operator", &unicode.IDS_Binary_Operator, reflect.TypeOf(unicode.IDS_Binary_Operator), ""),
		register.NewVar("IDS_Trinary_Operator", &unicode.IDS_Trinary_Operator, reflect.TypeOf(unicode.IDS_Trinary_Operator), ""),
		register.NewVar("Ideographic", &unicode.Ideographic, reflect.TypeOf(unicode.Ideographic), ""),
		register.NewVar("Imperial_Aramaic", &unicode.Imperial_Aramaic, reflect.TypeOf(unicode.Imperial_Aramaic), ""),
		register.NewFunction("In", unicode.In, ""),
		register.NewVar("Inherited", &unicode.Inherited, reflect.TypeOf(unicode.Inherited), ""),
		register.NewVar("Inscriptional_Pahlavi", &unicode.Inscriptional_Pahlavi, reflect.TypeOf(unicode.Inscriptional_Pahlavi), ""),
		register.NewVar("Inscriptional_Parthian", &unicode.Inscriptional_Parthian, reflect.TypeOf(unicode.Inscriptional_Parthian), ""),
		register.NewFunction("Is", unicode.Is, ""),
		register.NewFunction("IsControl", unicode.IsControl, ""),
		register.NewFunction("IsDigit", unicode.IsDigit, ""),
		register.NewFunction("IsGraphic", unicode.IsGraphic, ""),
		register.NewFunction("IsLetter", unicode.IsLetter, ""),
		register.NewFunction("IsLower", unicode.IsLower, ""),
		register.NewFunction("IsMark", unicode.IsMark, ""),
		register.NewFunction("IsNumber", unicode.IsNumber, ""),
		register.NewFunction("IsOneOf", unicode.IsOneOf, ""),
		register.NewFunction("IsPrint", unicode.IsPrint, ""),
		register.NewFunction("IsPunct", unicode.IsPunct, ""),
		register.NewFunction("IsSpace", unicode.IsSpace, ""),
		register.NewFunction("IsSymbol", unicode.IsSymbol, ""),
		register.NewFunction("IsTitle", unicode.IsTitle, ""),
		register.NewFunction("IsUpper", unicode.IsUpper, ""),
		register.NewVar("Javanese", &unicode.Javanese, reflect.TypeOf(unicode.Javanese), ""),
		register.NewVar("Join_Control", &unicode.Join_Control, reflect.TypeOf(unicode.Join_Control), ""),
		register.NewVar("Kaithi", &unicode.Kaithi, reflect.TypeOf(unicode.Kaithi), ""),
		register.NewVar("Kannada", &unicode.Kannada, reflect.TypeOf(unicode.Kannada), ""),
		register.NewVar("Katakana", &unicode.Katakana, reflect.TypeOf(unicode.Katakana), ""),
		register.NewVar("Kayah_Li", &unicode.Kayah_Li, reflect.TypeOf(unicode.Kayah_Li), ""),
		register.NewVar("Kharoshthi", &unicode.Kharoshthi, reflect.TypeOf(unicode.Kharoshthi), ""),
		register.NewVar("Khmer", &unicode.Khmer, reflect.TypeOf(unicode.Khmer), ""),
		register.NewVar("Khojki", &unicode.Khojki, reflect.TypeOf(unicode.Khojki), ""),
		register.NewVar("Khudawadi", &unicode.Khudawadi, reflect.TypeOf(unicode.Khudawadi), ""),
		register.NewVar("L", &unicode.L, reflect.TypeOf(unicode.L), ""),
		register.NewVar("Lao", &unicode.Lao, reflect.TypeOf(unicode.Lao), ""),
		register.NewVar("Latin", &unicode.Latin, reflect.TypeOf(unicode.Latin), ""),
		register.NewVar("Lepcha", &unicode.Lepcha, reflect.TypeOf(unicode.Lepcha), ""),
		register.NewVar("Letter", &unicode.Letter, reflect.TypeOf(unicode.Letter), ""),
		register.NewVar("Limbu", &unicode.Limbu, reflect.TypeOf(unicode.Limbu), ""),
		register.NewVar("Linear_A", &unicode.Linear_A, reflect.TypeOf(unicode.Linear_A), ""),
		register.NewVar("Linear_B", &unicode.Linear_B, reflect.TypeOf(unicode.Linear_B), ""),
		register.NewVar("Lisu", &unicode.Lisu, reflect.TypeOf(unicode.Lisu), ""),
		register.NewVar("Ll", &unicode.Ll, reflect.TypeOf(unicode.Ll), ""),
		register.NewVar("Lm", &unicode.Lm, reflect.TypeOf(unicode.Lm), ""),
		register.NewVar("Lo", &unicode.Lo, reflect.TypeOf(unicode.Lo), ""),
		register.NewVar("Logical_Order_Exception", &unicode.Logical_Order_Exception, reflect.TypeOf(unicode.Logical_Order_Exception), ""),
		register.NewVar("Lower", &unicode.Lower, reflect.TypeOf(unicode.Lower), ""),
		register.NewConst("LowerCase", unicode.LowerCase, ""),
		register.NewVar("Lt", &unicode.Lt, reflect.TypeOf(unicode.Lt), ""),
		register.NewVar("Lu", &unicode.Lu, reflect.TypeOf(unicode.Lu), ""),
		register.NewVar("Lycian", &unicode.Lycian, reflect.TypeOf(unicode.Lycian), ""),
		register.NewVar("Lydian", &unicode.Lydian, reflect.TypeOf(unicode.Lydian), ""),
		register.NewVar("M", &unicode.M, reflect.TypeOf(unicode.M), ""),
		register.NewVar("Mahajani", &unicode.Mahajani, reflect.TypeOf(unicode.Mahajani), ""),
		register.NewVar("Makasar", &unicode.Makasar, reflect.TypeOf(unicode.Makasar), ""),
		register.NewVar("Malayalam", &unicode.Malayalam, reflect.TypeOf(unicode.Malayalam), ""),
		register.NewVar("Mandaic", &unicode.Mandaic, reflect.TypeOf(unicode.Mandaic), ""),
		register.NewVar("Manichaean", &unicode.Manichaean, reflect.TypeOf(unicode.Manichaean), ""),
		register.NewVar("Marchen", &unicode.Marchen, reflect.TypeOf(unicode.Marchen), ""),
		register.NewVar("Mark", &unicode.Mark, reflect.TypeOf(unicode.Mark), ""),
		register.NewVar("Masaram_Gondi", &unicode.Masaram_Gondi, reflect.TypeOf(unicode.Masaram_Gondi), ""),
		register.NewConst("MaxASCII", unicode.MaxASCII, ""),
		register.NewConst("MaxCase", unicode.MaxCase, ""),
		register.NewConst("MaxLatin1", unicode.MaxLatin1, ""),
		register.NewConst("MaxRune", unicode.MaxRune, ""),
		register.NewVar("Mc", &unicode.Mc, reflect.TypeOf(unicode.Mc), ""),
		register.NewVar("Me", &unicode.Me, reflect.TypeOf(unicode.Me), ""),
		register.NewVar("Medefaidrin", &unicode.Medefaidrin, reflect.TypeOf(unicode.Medefaidrin), ""),
		register.NewVar("Meetei_Mayek", &unicode.Meetei_Mayek, reflect.TypeOf(unicode.Meetei_Mayek), ""),
		register.NewVar("Mende_Kikakui", &unicode.Mende_Kikakui, reflect.TypeOf(unicode.Mende_Kikakui), ""),
		register.NewVar("Meroitic_Cursive", &unicode.Meroitic_Cursive, reflect.TypeOf(unicode.Meroitic_Cursive), ""),
		register.NewVar("Meroitic_Hieroglyphs", &unicode.Meroitic_Hieroglyphs, reflect.TypeOf(unicode.Meroitic_Hieroglyphs), ""),
		register.NewVar("Miao", &unicode.Miao, reflect.TypeOf(unicode.Miao), ""),
		register.NewVar("Mn", &unicode.Mn, reflect.TypeOf(unicode.Mn), ""),
		register.NewVar("Modi", &unicode.Modi, reflect.TypeOf(unicode.Modi), ""),
		register.NewVar("Mongolian", &unicode.Mongolian, reflect.TypeOf(unicode.Mongolian), ""),
		register.NewVar("Mro", &unicode.Mro, reflect.TypeOf(unicode.Mro), ""),
		register.NewVar("Multani", &unicode.Multani, reflect.TypeOf(unicode.Multani), ""),
		register.NewVar("Myanmar", &unicode.Myanmar, reflect.TypeOf(unicode.Myanmar), ""),
		register.NewVar("N", &unicode.N, reflect.TypeOf(unicode.N), ""),
		register.NewVar("Nabataean", &unicode.Nabataean, reflect.TypeOf(unicode.Nabataean), ""),
		register.NewVar("Nandinagari", &unicode.Nandinagari, reflect.TypeOf(unicode.Nandinagari), ""),
		register.NewVar("Nd", &unicode.Nd, reflect.TypeOf(unicode.Nd), ""),
		register.NewVar("New_Tai_Lue", &unicode.New_Tai_Lue, reflect.TypeOf(unicode.New_Tai_Lue), ""),
		register.NewVar("Newa", &unicode.Newa, reflect.TypeOf(unicode.Newa), ""),
		register.NewVar("Nko", &unicode.Nko, reflect.TypeOf(unicode.Nko), ""),
		register.NewVar("Nl", &unicode.Nl, reflect.TypeOf(unicode.Nl), ""),
		register.NewVar("No", &unicode.No, reflect.TypeOf(unicode.No), ""),
		register.NewVar("Noncharacter_Code_Point", &unicode.Noncharacter_Code_Point, reflect.TypeOf(unicode.Noncharacter_Code_Point), ""),
		register.NewVar("Number", &unicode.Number, reflect.TypeOf(unicode.Number), ""),
		register.NewVar("Nushu", &unicode.Nushu, reflect.TypeOf(unicode.Nushu), ""),
		register.NewVar("Nyiakeng_Puachue_Hmong", &unicode.Nyiakeng_Puachue_Hmong, reflect.TypeOf(unicode.Nyiakeng_Puachue_Hmong), ""),
		register.NewVar("Ogham", &unicode.Ogham, reflect.TypeOf(unicode.Ogham), ""),
		register.NewVar("Ol_Chiki", &unicode.Ol_Chiki, reflect.TypeOf(unicode.Ol_Chiki), ""),
		register.NewVar("Old_Hungarian", &unicode.Old_Hungarian, reflect.TypeOf(unicode.Old_Hungarian), ""),
		register.NewVar("Old_Italic", &unicode.Old_Italic, reflect.TypeOf(unicode.Old_Italic), ""),
		register.NewVar("Old_North_Arabian", &unicode.Old_North_Arabian, reflect.TypeOf(unicode.Old_North_Arabian), ""),
		register.NewVar("Old_Permic", &unicode.Old_Permic, reflect.TypeOf(unicode.Old_Permic), ""),
		register.NewVar("Old_Persian", &unicode.Old_Persian, reflect.TypeOf(unicode.Old_Persian), ""),
		register.NewVar("Old_Sogdian", &unicode.Old_Sogdian, reflect.TypeOf(unicode.Old_Sogdian), ""),
		register.NewVar("Old_South_Arabian", &unicode.Old_South_Arabian, reflect.TypeOf(unicode.Old_South_Arabian), ""),
		register.NewVar("Old_Turkic", &unicode.Old_Turkic, reflect.TypeOf(unicode.Old_Turkic), ""),
		register.NewVar("Oriya", &unicode.Oriya, reflect.TypeOf(unicode.Oriya), ""),
		register.NewVar("Osage", &unicode.Osage, reflect.TypeOf(unicode.Osage), ""),
		register.NewVar("Osmanya", &unicode.Osmanya, reflect.TypeOf(unicode.Osmanya), ""),
		register.NewVar("Other", &unicode.Other, reflect.TypeOf(unicode.Other), ""),
		register.NewVar("Other_Alphabetic", &unicode.Other_Alphabetic, reflect.TypeOf(unicode.Other_Alphabetic), ""),
		register.NewVar("Other_Default_Ignorable_Code_Point", &unicode.Other_Default_Ignorable_Code_Point, reflect.TypeOf(unicode.Other_Default_Ignorable_Code_Point), ""),
		register.NewVar("Other_Grapheme_Extend", &unicode.Other_Grapheme_Extend, reflect.TypeOf(unicode.Other_Grapheme_Extend), ""),
		register.NewVar("Other_ID_Continue", &unicode.Other_ID_Continue, reflect.TypeOf(unicode.Other_ID_Continue), ""),
		register.NewVar("Other_ID_Start", &unicode.Other_ID_Start, reflect.TypeOf(unicode.Other_ID_Start), ""),
		register.NewVar("Other_Lowercase", &unicode.Other_Lowercase, reflect.TypeOf(unicode.Other_Lowercase), ""),
		register.NewVar("Other_Math", &unicode.Other_Math, reflect.TypeOf(unicode.Other_Math), ""),
		register.NewVar("Other_Uppercase", &unicode.Other_Uppercase, reflect.TypeOf(unicode.Other_Uppercase), ""),
		register.NewVar("P", &unicode.P, reflect.TypeOf(unicode.P), ""),
		register.NewVar("Pahawh_Hmong", &unicode.Pahawh_Hmong, reflect.TypeOf(unicode.Pahawh_Hmong), ""),
		register.NewVar("Palmyrene", &unicode.Palmyrene, reflect.TypeOf(unicode.Palmyrene), ""),
		register.NewVar("Pattern_Syntax", &unicode.Pattern_Syntax, reflect.TypeOf(unicode.Pattern_Syntax), ""),
		register.NewVar("Pattern_White_Space", &unicode.Pattern_White_Space, reflect.TypeOf(unicode.Pattern_White_Space), ""),
		register.NewVar("Pau_Cin_Hau", &unicode.Pau_Cin_Hau, reflect.TypeOf(unicode.Pau_Cin_Hau), ""),
		register.NewVar("Pc", &unicode.Pc, reflect.TypeOf(unicode.Pc), ""),
		register.NewVar("Pd", &unicode.Pd, reflect.TypeOf(unicode.Pd), ""),
		register.NewVar("Pe", &unicode.Pe, reflect.TypeOf(unicode.Pe), ""),
		register.NewVar("Pf", &unicode.Pf, reflect.TypeOf(unicode.Pf), ""),
		register.NewVar("Phags_Pa", &unicode.Phags_Pa, reflect.TypeOf(unicode.Phags_Pa), ""),
		register.NewVar("Phoenician", &unicode.Phoenician, reflect.TypeOf(unicode.Phoenician), ""),
		register.NewVar("Pi", &unicode.Pi, reflect.TypeOf(unicode.Pi), ""),
		register.NewVar("Po", &unicode.Po, reflect.TypeOf(unicode.Po), ""),
		register.NewVar("Prepended_Concatenation_Mark", &unicode.Prepended_Concatenation_Mark, reflect.TypeOf(unicode.Prepended_Concatenation_Mark), ""),
		register.NewVar("PrintRanges", &unicode.PrintRanges, reflect.TypeOf(unicode.PrintRanges), ""),
		register.NewVar("Properties", &unicode.Properties, reflect.TypeOf(unicode.Properties), ""),
		register.NewVar("Ps", &unicode.Ps, reflect.TypeOf(unicode.Ps), ""),
		register.NewVar("Psalter_Pahlavi", &unicode.Psalter_Pahlavi, reflect.TypeOf(unicode.Psalter_Pahlavi), ""),
		register.NewVar("Punct", &unicode.Punct, reflect.TypeOf(unicode.Punct), ""),
		register.NewVar("Quotation_Mark", &unicode.Quotation_Mark, reflect.TypeOf(unicode.Quotation_Mark), ""),
		register.NewVar("Radical", &unicode.Radical, reflect.TypeOf(unicode.Radical), ""),
		register.NewType("Range16", reflect.TypeOf(func(unicode.Range16) {}).In(0), ""),
		register.NewType("Range32", reflect.TypeOf(func(unicode.Range32) {}).In(0), ""),
		register.NewType("RangeTable", reflect.TypeOf(func(unicode.RangeTable) {}).In(0), ""),
		register.NewVar("Regional_Indicator", &unicode.Regional_Indicator, reflect.TypeOf(unicode.Regional_Indicator), ""),
		register.NewVar("Rejang", &unicode.Rejang, reflect.TypeOf(unicode.Rejang), ""),
		register.NewConst("ReplacementChar", unicode.ReplacementChar, ""),
		register.NewVar("Runic", &unicode.Runic, reflect.TypeOf(unicode.Runic), ""),
		register.NewVar("S", &unicode.S, reflect.TypeOf(unicode.S), ""),
		register.NewVar("STerm", &unicode.STerm, reflect.TypeOf(unicode.STerm), ""),
		register.NewVar("Samaritan", &unicode.Samaritan, reflect.TypeOf(unicode.Samaritan), ""),
		register.NewVar("Saurashtra", &unicode.Saurashtra, reflect.TypeOf(unicode.Saurashtra), ""),
		register.NewVar("Sc", &unicode.Sc, reflect.TypeOf(unicode.Sc), ""),
		register.NewVar("Scripts", &unicode.Scripts, reflect.TypeOf(unicode.Scripts), ""),
		register.NewVar("Sentence_Terminal", &unicode.Sentence_Terminal, reflect.TypeOf(unicode.Sentence_Terminal), ""),
		register.NewVar("Sharada", &unicode.Sharada, reflect.TypeOf(unicode.Sharada), ""),
		register.NewVar("Shavian", &unicode.Shavian, reflect.TypeOf(unicode.Shavian), ""),
		register.NewVar("Siddham", &unicode.Siddham, reflect.TypeOf(unicode.Siddham), ""),
		register.NewVar("SignWriting", &unicode.SignWriting, reflect.TypeOf(unicode.SignWriting), ""),
		register.NewFunction("SimpleFold", unicode.SimpleFold, ""),
		register.NewVar("Sinhala", &unicode.Sinhala, reflect.TypeOf(unicode.Sinhala), ""),
		register.NewVar("Sk", &unicode.Sk, reflect.TypeOf(unicode.Sk), ""),
		register.NewVar("Sm", &unicode.Sm, reflect.TypeOf(unicode.Sm), ""),
		register.NewVar("So", &unicode.So, reflect.TypeOf(unicode.So), ""),
		register.NewVar("Soft_Dotted", &unicode.Soft_Dotted, reflect.TypeOf(unicode.Soft_Dotted), ""),
		register.NewVar("Sogdian", &unicode.Sogdian, reflect.TypeOf(unicode.Sogdian), ""),
		register.NewVar("Sora_Sompeng", &unicode.Sora_Sompeng, reflect.TypeOf(unicode.Sora_Sompeng), ""),
		register.NewVar("Soyombo", &unicode.Soyombo, reflect.TypeOf(unicode.Soyombo), ""),
		register.NewVar("Space", &unicode.Space, reflect.TypeOf(unicode.Space), ""),
		register.NewType("SpecialCase", reflect.TypeOf(func(unicode.SpecialCase) {}).In(0), ""),
		register.NewVar("Sundanese", &unicode.Sundanese, reflect.TypeOf(unicode.Sundanese), ""),
		register.NewVar("Syloti_Nagri", &unicode.Syloti_Nagri, reflect.TypeOf(unicode.Syloti_Nagri), ""),
		register.NewVar("Symbol", &unicode.Symbol, reflect.TypeOf(unicode.Symbol), ""),
		register.NewVar("Syriac", &unicode.Syriac, reflect.TypeOf(unicode.Syriac), ""),
		register.NewVar("Tagalog", &unicode.Tagalog, reflect.TypeOf(unicode.Tagalog), ""),
		register.NewVar("Tagbanwa", &unicode.Tagbanwa, reflect.TypeOf(unicode.Tagbanwa), ""),
		register.NewVar("Tai_Le", &unicode.Tai_Le, reflect.TypeOf(unicode.Tai_Le), ""),
		register.NewVar("Tai_Tham", &unicode.Tai_Tham, reflect.TypeOf(unicode.Tai_Tham), ""),
		register.NewVar("Tai_Viet", &unicode.Tai_Viet, reflect.TypeOf(unicode.Tai_Viet), ""),
		register.NewVar("Takri", &unicode.Takri, reflect.TypeOf(unicode.Takri), ""),
		register.NewVar("Tamil", &unicode.Tamil, reflect.TypeOf(unicode.Tamil), ""),
		register.NewVar("Tangut", &unicode.Tangut, reflect.TypeOf(unicode.Tangut), ""),
		register.NewVar("Telugu", &unicode.Telugu, reflect.TypeOf(unicode.Telugu), ""),
		register.NewVar("Terminal_Punctuation", &unicode.Terminal_Punctuation, reflect.TypeOf(unicode.Terminal_Punctuation), ""),
		register.NewVar("Thaana", &unicode.Thaana, reflect.TypeOf(unicode.Thaana), ""),
		register.NewVar("Thai", &unicode.Thai, reflect.TypeOf(unicode.Thai), ""),
		register.NewVar("Tibetan", &unicode.Tibetan, reflect.TypeOf(unicode.Tibetan), ""),
		register.NewVar("Tifinagh", &unicode.Tifinagh, reflect.TypeOf(unicode.Tifinagh), ""),
		register.NewVar("Tirhuta", &unicode.Tirhuta, reflect.TypeOf(unicode.Tirhuta), ""),
		register.NewVar("Title", &unicode.Title, reflect.TypeOf(unicode.Title), ""),
		register.NewConst("TitleCase", unicode.TitleCase, ""),
		register.NewFunction("To", unicode.To, ""),
		register.NewFunction("ToLower", unicode.ToLower, ""),
		register.NewFunction("ToTitle", unicode.ToTitle, ""),
		register.NewFunction("ToUpper", unicode.ToUpper, ""),
		register.NewVar("TurkishCase", &unicode.TurkishCase, reflect.TypeOf(unicode.TurkishCase), ""),
		register.NewVar("Ugaritic", &unicode.Ugaritic, reflect.TypeOf(unicode.Ugaritic), ""),
		register.NewVar("Unified_Ideograph", &unicode.Unified_Ideograph, reflect.TypeOf(unicode.Unified_Ideograph), ""),
		register.NewVar("Upper", &unicode.Upper, reflect.TypeOf(unicode.Upper), ""),
		register.NewConst("UpperCase", unicode.UpperCase, ""),
		register.NewConst("UpperLower", unicode.UpperLower, ""),
		register.NewVar("Vai", &unicode.Vai, reflect.TypeOf(unicode.Vai), ""),
		register.NewVar("Variation_Selector", &unicode.Variation_Selector, reflect.TypeOf(unicode.Variation_Selector), ""),
		register.NewConst("Version", unicode.Version, ""),
		register.NewVar("Wancho", &unicode.Wancho, reflect.TypeOf(unicode.Wancho), ""),
		register.NewVar("Warang_Citi", &unicode.Warang_Citi, reflect.TypeOf(unicode.Warang_Citi), ""),
		register.NewVar("White_Space", &unicode.White_Space, reflect.TypeOf(unicode.White_Space), ""),
		register.NewVar("Yi", &unicode.Yi, reflect.TypeOf(unicode.Yi), ""),
		register.NewVar("Z", &unicode.Z, reflect.TypeOf(unicode.Z), ""),
		register.NewVar("Zanabazar_Square", &unicode.Zanabazar_Square, reflect.TypeOf(unicode.Zanabazar_Square), ""),
		register.NewVar("Zl", &unicode.Zl, reflect.TypeOf(unicode.Zl), ""),
		register.NewVar("Zp", &unicode.Zp, reflect.TypeOf(unicode.Zp), ""),
		register.NewVar("Zs", &unicode.Zs, reflect.TypeOf(unicode.Zs), ""),
	)
}
